routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes([
    'register' => false
]);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('company', CompanyController::class);
    Route::resource('employee', EmployeeController::class);
});

app/Models/Employees.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Employees extends Model
{
    use HasFactory;

    protected $fillable = [
        'first_name',
        'last_name',
        'company',
        'email',
        'phone'
    ];

    /**
     * Relationship with Company
     *
     * @return BelongsTo
     */
    public function Company() {
        return $this->belongsTo(Companies::class, 'company');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Companies;
use App\Models\Employees;
use Crypt;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class EmployeeController extends Controller
{
    /**
     * Returning the Employees list.
     *
     * @return Application|Factory|View
     */
    public function index() {
        $employees = Employees::latest()->paginate(10);
        return view('pages.employees.index', compact('employees'));
    }

    /**
     * Returning Employee Create Form.
     *
     * @return Application|Factory|View
     */
    public function create() {
        $companies = Companies::all();
        return view('pages.employees.create', compact('companies'));
    }

    /**
     * Creating new employee in database.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request) {
        $data = $this->validate($request, [
            'first_name' => 'required|string|min:2',
            'last_name' => 'required|string|min:2',
            'company' => 'required|integer|exists:companies,id',
            'email' => 'nullable|email|unique:employees,email',
            'phone' => 'nullable|integer|digits:10'
        ]);
        $create = Employees::create($data);
        if ($create !== null) {
            return redirect()->route('employee.index')->with('success', 'Employee Created Successfully');
        }
        return redirect()->back()->with('error', 'Something Went Wrong');
    }

    /**
     * Showing Single Employee
     *
     * @param $id
     * @return Application|Factory|View
     */
    public function show($id) {
        $id = $this->IdCrypt($id);
        $employee = Employees::find($id);
        return view('pages.employees.view', compact('employee'));
    }

    /**
     * Editing Page of Employee
     *
     * @param $id
     * @return Application|Factory|View
     */
    public function edit($id) {
        $id = $this->IdCrypt($id);
        $employee = Employees::find($id);
        $companies = Companies::all();
        return view('pages.employees.edit', compact('employee', 'companies'));
    }

    /**
     * Updating Employee Details.
     *
     * @param Request $request
     * @param $id
     * @return RedirectResponse
     */
    public function update(Request $request, $id) {
        $id = $this->IdCrypt($id);
        $employee = Employees::find($id);
        $data = $this->validate($request, [
            'first_name' => 'required|string|min:2',
            'last_name' => 'required|string|min:2',
            'company' => 'required|integer|exists:companies,id',
            'email' => 'nullable|email',
            'phone' => 'nullable|integer|digits:10'
        ]);
        $update = $employee->update($data);
        if ($update !== true) {
            return redirect()->back()->with('error', 'Something Went Wrong');
        }
        return redirect()->route('employee.index')->with('success', 'Employee Updated Successfully');
    }

    /**
     * Deleting Employee from records
     *
     * @param $id
     * @return RedirectResponse
     */
    public function destroy($id) {
        $id = $this->IdCrypt($id);
        $employee = Employees::find($id);
        $delete = $employee->delete();
        if ($delete !== true) {
            return redirect()->back()->with('error', 'Something Went Wrong');
        }
        return redirect()->back()->with('success', 'Deleted Successfully');
    }

    /**
     * Decrypting ID using crypt
     *
     * @param $id
     * @return mixed
     */
    public function IdCrypt($id) {
        $id = htmlspecialchars(stripslashes($id));
        return Crypt::decrypt($id);
    }
}

resources/views/pages/employees/create.blade.php
@extends('layouts.app')

@section('title', 'Create Employee')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">{{ __('Employee Create Form') }}</div>
                    <div class="card-body">
                        @if (session('success'))
                            <div class="alert alert-success" role="alert">
                                {{ session('success') }}
                            </div>
                        @endif
                        @if (session('error'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('error') }}
                            </div>
                        @endif
                        <form method="POST" action="{{ route('employee.store') }}">@csrf
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label for="FirstName" class="form-label">First Name of Employee</label>
                                    <input id="FirstName" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ old('first_name') }}" required autocomplete="first_name" autofocus>
                                    @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="LastName" class="form-label">Last Name of Employee</label>
                                    <input id="LastName" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ old('last_name') }}" required autocomplete="last_name">
                                    @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="CompanyID" class="form-label">Company of Employee</label>
                                    <select name="company" id="CompanyID" class="form-select form-control" required>
                                        <option value="">Select the Employee Company</option>
                                        @forelse($companies as $company)
                                            <option value="{{ $company->id }}" @if(old('company') == $company->id) selected @endif>{{ $company->name }}</option>
                                        @empty
                                        @endforelse
                                    </select>
                                    @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="EmailId" class="form-label">Email of Employee</label>
                                    <input id="EmailId" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" autocomplete="email">
                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="PhoneNumber" class="form-label">Phone Number of Employee</label>
                                    <input id="PhoneNumber" type="phone" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') }}" autocomplete="phone">
                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mt-3">
                                <div class="col-md-12 d-flex justify-content-center">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/employees/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Employee')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">{{ __('Employee Details Editing Form') }}</div>
                    <div class="card-body">
                        @if (session('success'))
                            <div class="alert alert-success" role="alert">
                                {{ session('success') }}
                            </div>
                        @endif
                        @if (session('error'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('error') }}
                            </div>
                        @endif
                        <form method="POST" action="{{ route('employee.update', Crypt::encrypt($employee['id'])) }}">@csrf {{ method_field('PUT') }}
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label for="FirstName" class="form-label">First Name of Employee</label>
                                    <input id="FirstName" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ $employee['first_name'] }}" required autocomplete="first_name">
                                    @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="LastName" class="form-label">Last Name of Employee</label>
                                    <input id="LastName" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ $employee['last_name'] }}" required autocomplete="last_name">
                                    @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="CompanyID" class="form-label">Company of Employee</label>
                                    <select name="company" id="CompanyID" class="form-select form-control" required>
                                        <option value="">Select the Employee Company</option>
                                        @forelse($companies as $company)
                                            <option value="{{ $company->id }}" @if($employee['company'] == $company->id) selected @endif>{{ $company->name }}</option>
                                        @empty
                                        @endforelse
                                    </select>
                                    @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="EmailId" class="form-label">Email of Employee</label>
                                    <input id="EmailId" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $employee['email'] }}" autocomplete="email">
                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="PhoneNumber" class="form-label">Phone Number of Employee</label>
                                    <input id="PhoneNumber" type="phone" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ $employee['phone'] }}" autocomplete="phone">
                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mt-3">
                                <div class="col-md-12 d-flex justify-content-center">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Update') }}
                                    </button>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{{ route('employee.index') }}" class="btn btn-secondary">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/employees/index.blade.php
@extends('layouts.app')

@section('title', 'Employees Listing')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">{{ __('Employees Listing') }}</div>

                    <div class="card-body">
                        @if (session('success'))
                            <div class="alert alert-success" role="alert">
                                {{ session('success') }}
                            </div>
                        @endif
                        @if (session('error'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('error') }}
                            </div>
                        @endif
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Company Name</th>
                                    <th scope="col">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($employees as $key=>$employee)
                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $employee['first_name'].' '.$employee['last_name'] }}</td>
                                        <td>{{ $employee['email'] ?? 'Not Available' }}</td>
                                        <td>{{ $employee->Company->name }}</td>
                                        <td><a href="{{ route('employee.show', Crypt::encrypt($employee['id'])) }}" class="btn btn-primary">View</a>&nbsp;&nbsp;&nbsp;<a href="{{ route('employee.edit', Crypt::encrypt($employee['id'])) }}" class="btn btn-secondary">Edit</a>&nbsp;&nbsp;&nbsp;<a class="btn btn-danger" onclick="event.preventDefault(); document.getElementById('delete-form{{$key}}').submit();">Delete</a>
                                            <form id="delete-form{{$key}}" method="post" action="{{ route('employee.destroy', Crypt::encrypt($employee['id'])) }}" class="d-none">@csrf {{ method_field('DELETE') }}</form>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5" class="text-center">No Records Available!</td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                            {!! $employees->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/employees/view.blade.php
@extends('layouts.app')

@section('title', 'Employee Detail')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Employee View Page') }}</div>

                    <div class="card-body">
                        <div class="container row">
                            <div class="col-md-6">
                                <h4>First Name: <span class="text-black">{{ $employee['first_name'] }}</span></h4>
                            </div>
                            <div class="col-md-6">
                                <h4>Last Name: <span class="text-black">{{ $employee['last_name'] }}</span></h4>
                            </div>
                            <div class="col-md-6 mt-3">
                                <h5>Company: <span class="text-black">{{ $employee->Company->name }}</span></h5>
                            </div>
                            <div class="col-md-6 mt-3">
                                <h5>Email: <span class="text-black">{{ $employee['email'] }}</span></h5>
                                <h5>Phone: <span class="text-black">{{ $employee['phone'] }}</span></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection