routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes([
    'register' => false
]);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('company', CompanyController::class);
    Route::resource('employee', EmployeeController::class);
});

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Companies;
use Crypt;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Image;
use Storage;

class CompanyController extends Controller
{
    /**
     * Displaying all companies available in database
     *
     * @return Application|Factory|View
     */
    public function index() {
        $companies = Companies::latest()->paginate(10);
        return view('pages.companies.index', compact('companies'));
    }

    /**
     * Rendering Create Company Form
     *
     * @return Application|Factory|View
     */
    public function create() {
        return view('pages.companies.create');
    }

    /**
     * Storing New Company Information in Database;
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request) {
        $data = $this->validate($request, [
            'name' => 'required|string',
            'email' => 'nullable|email|unique:companies,email',
            'logo' => 'nullable|image|mimes:jpeg,jpg,png,svg',
            'website' => 'nullable|url'
        ]);
        $name = null;
        if ($request->hasFile('logo')) {
            $file = $request->file('logo');
            $add = rand(1, 1000).$data['name'];
            $name = $add.$file->getClientOriginalName();
            Image::make($file->getRealPath())->resize('100', 100)->save(storage_path('app/public').$name, '100');
        }
        $create = Companies::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'logo' => $name,
            'website' => $data['website']
        ]);
        if ($create !== null) {
            return redirect()->route('company.index')->with('success', 'Company Created Successfully');
        }
        return redirect()->back()->with('error', 'Something Went Wrong');

    }

    /**
     * Viewing a single company details
     *
     * @param $id
     * @return Application|Factory|View
     */
    public function show($id) {
        $id = $this->IdDecrypt($id);
        $company = Companies::find($id);
        return view('pages.companies.view', compact('company'));
    }

    /**
     * Returning Edit form for company editing
     *
     * @param $id
     * @return Application|Factory|View
     */
    public function edit($id) {
        $id = $this->IdDecrypt($id);
        $company = Companies::find($id);
        return view('pages.companies.edit', compact('company'));
    }

    /**
     * Updating the company records in database.
     *
     * @param Request $request
     * @param $id
     * @return RedirectResponse
     */
    public function update(Request $request, $id) {
        $data = $this->validate($request, [
            'name' => 'required|string',
            'email' => 'nullable|email',
            'logo' => 'nullable|image|mimes:jpeg,jpg,png,svg',
            'website' => 'nullable|url'
        ]);
        $id = $this->IdDecrypt($id);
        $company = Companies::find($id);
        $logo = $company['logo'];
        if ($request->hasFile('logo')) {
            $file = $request->file('logo');
            $add = rand(1, 1000).$data['name'];
            $name = $add.$file->getClientOriginalName();
            Image::make($file->getRealPath())->resize('100', 100)->save(storage_path('app/public').$name, '100');
            $logo = $name;
        }
        $update = $company->update([
            'name' => $data['name'],
            'email' => $data['email'],
            'logo' => $logo,
            'website' => $data['website']
        ]);
        if ($update !== true) {
            return redirect()->back()->with('error', 'Something Went Wrong');
        }
        return redirect()->route('company.index')->with('success', 'Company Updated Successfully');
    }

    /**
     * Deleting the Company from database.
     *
     * @param $id
     * @return RedirectResponse
     */
    public function destroy($id) {
        $id = $this->IdDecrypt($id);
        $company = Companies::find($id);
        $status = $company->delete();
        if ($status !== true) {
            return redirect()->back()->with('error', 'Something Went Wrong');
        }
        return redirect()->back()->with('success', 'Deleted Successfully');
    }

    private function IdDecrypt($id) {
        $id = htmlspecialchars(stripslashes($id));
        return Crypt::decrypt($id);
    }
}

resources/views/pages/companies/create.blade.php
@extends('layouts.app')

@section('title', 'Create Company')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">{{ __('Create Company Form') }}</div>

                    <div class="card-body">
                        @if (session('success'))
                            <div class="alert alert-success" role="alert">
                                {{ session('success') }}
                            </div>
                        @endif
                        @if (session('error'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('error') }}
                            </div>
                        @endif
                        <div class="container">
                            <form action="{{ route('company.store') }}" method="post" enctype="multipart/form-data">@csrf
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="CompanyName" class="form-label">Enter name of Company</label>
                                            <input type="text" name="name" id="CompanyName" class="form-control @error('name') is-invalid @enderror" placeholder="Enter name of company" value="{{ old('name') }}" required>
                                            @error('name')
                                            <span class="text-danger is-invalid text-sm-start">{{$message}}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="CompanyEmail" class="form-label">Enter email of Company</label>
                                            <input type="email" name="email" id="CompanyEmail" class="form-control @error('email') is-invalid @enderror" placeholder="Enter email of company" value="{{ old('email') }}">
                                            @error('email')
                                            <span class="text-danger is-invalid text-sm-start">{{$message}}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="CompanyLogo" class="form-label">Select Logo of company</label>
                                            <input type="file" name="logo" accept="image/png, image/jpeg, image/svg" id="CompanyLogo" class="form-control @error('logo') is-invalid @enderror" placeholder="Select logo of company">
                                            @error('logo')
                                            <span class="text-danger is-invalid text-sm-start">{{$message}}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="CompanyWebsite" class="form-label">Enter Website of Company</label>
                                            <input type="url" name="website" id="CompanyWebsite" class="form-control @error('website') is-invalid @enderror" placeholder="Enter Website of company" value="{{ old('website') }}">
                                            @error('website')
                                            <span class="text-danger is-invalid text-sm-start">{{$message}}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-12 d-flex justify-content-center mt-3">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/companies/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Company')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">{{ __('Edit Company Form') }}</div>

                    <div class="card-body">
                        @if (session('success'))
                            <div class="alert alert-success" role="alert">
                                {{ session('success') }}
                            </div>
                        @endif
                        @if (session('error'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('error') }}
                            </div>
                        @endif
                        <div class="container">
                            <form action="{{ route('company.update', Crypt::encrypt($company->id)) }}" method="post" enctype="multipart/form-data">@csrf {{ method_field('PUT') }}
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="CompanyName" class="form-label">Name of Company</label>
                                            <input type="text" name="name" id="CompanyName" class="form-control @error('name') is-invalid @enderror" placeholder="Enter name of company" value="{{ $company->name }}" required>
                                            @error('name')
                                            <span class="text-danger is-invalid text-sm-start">{{$message}}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="CompanyEmail" class="form-label">Email of Company</label>
                                            <input type="email" name="email" id="CompanyEmail" class="form-control @error('email') is-invalid @enderror" placeholder="Enter email of company" value="{{ $company->email }}">
                                            @error('email')
                                            <span class="text-danger is-invalid text-sm-start">{{$message}}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="CompanyLogo" class="form-label">Logo of company</label>
                                            <input type="file" name="logo" accept="image/png, image/jpeg, image/svg" id="CompanyLogo" class="form-control @error('logo') is-invalid @enderror" placeholder="Select logo of company">
                                            @error('logo')
                                            <span class="text-danger is-invalid text-sm-start">{{$message}}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="CompanyWebsite" class="form-label">Website of Company</label>
                                            <input type="url" name="website" id="CompanyWebsite" class="form-control @error('website') is-invalid @enderror" placeholder="Enter Website of company" value="{{ $company->website }}">
                                            @error('website')
                                            <span class="text-danger is-invalid text-sm-start">{{$message}}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-12 d-flex justify-content-center mt-3">
                                        <button type="submit" class="btn btn-primary">Submit</button>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{{ route('company.index') }}" class="btn btn-primary">Cancel</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/companies/index.blade.php
@extends('layouts.app')

@section('title', 'Companies Listing')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">{{ __('Companies List') }}</div>
                    <div class="card-body">
                        @if (session('success'))
                            <div class="alert alert-success" role="alert">
                                {{ session('success') }}
                            </div>
                        @endif
                        @if (session('error'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('error') }}
                            </div>
                        @endif
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Logo</th>
                                    <th scope="col">Company Name</th>
                                    <th scope="col">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($companies as $key=>$company)
                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td><img src="{!! asset("storage/$company->logo") !!}" alt="{{ $company->name }}" class="img-thumbnail img-fluid" width="50"></td>
                                        <td>{{ $company['name'] }}</td>
                                        <td><a href="{{ route('company.show', Crypt::encrypt($company['id'])) }}" class="btn btn-primary">View</a>&nbsp;&nbsp;&nbsp;<a href="{{ route('company.edit', Crypt::encrypt($company['id'])) }}" class="btn btn-secondary">Edit</a>&nbsp;&nbsp;&nbsp;<a class="btn btn-danger" onclick="event.preventDefault(); document.getElementById('delete-form{{$key}}').submit();">Delete</a><form id="delete-form{{$key}}" method="post" action="{{ route('company.destroy', Crypt::encrypt($company['id'])) }}" class="d-none">@csrf {{ method_field('DELETE') }}</form>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="4" class="text-center">No Records Available!</td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                            {!! $companies->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/companies/view.blade.php
@extends('layouts.app')

@section('title', 'Company Detail')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">{{ $company->name }} Information</div>
                    <div class="card-body">
                        <div class="container">
                            <div class="row mb-3">
                                <div class="col-md-6 d-flex justify-content-center">
                                    <img src="{!! asset("storage/$company->logo") !!}" alt="image">
                                </div>
                                <div class="col-md-6 justify-content-center">
                                    <h3 class="mb-4">Company : <span class="text-dark">{{ $company->name }}</span></h3>
                                    <h5>Email : <a class="text-black" href="mailto:{{ $company->email }}">{{ $company->email }}</a></h5>
                                    <h5>Website : <a class="text-black" href="{{ $company->website }}">{{ $company->website }}</a></h5>
                                </div>
                            </div>
                            <div class="table-responsive mt-5">
                                <h3 class="text-black text-center mt-5">{{ __('List of Employees in This Company!') }}</h3>
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @forelse($company->Employees as $key=>$employee)
                                        <tr>
                                            <td>{{ $key+1 }}</td>
                                            <td>{{ $employee['first_name'].' '.$employee['last_name'] }}</td>
                                            <td>{{ $employee['email'] ?? 'Not Available' }}</td>
                                            <td><a href="{{ route('employee.show', Crypt::encrypt($employee['id'])) }}" class="btn btn-primary">View</a>&nbsp;&nbsp;&nbsp;<a href="{{ route('employee.edit', Crypt::encrypt($employee['id'])) }}" class="btn btn-secondary">Edit</a>&nbsp;&nbsp;&nbsp;<a class="btn btn-danger" onclick="event.preventDefault(); document.getElementById('delete-form{{$key}}').submit();">Delete</a>
                                                <form id="delete-form{{$key}}" method="post" action="{{ route('employee.destroy', Crypt::encrypt($employee['id'])) }}" class="d-none">@csrf {{ method_field('DELETE') }}</form>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="4" class="text-center">No Records Available!</td>
                                        </tr>
                                    @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection